### ISSUE TITLE
number notation

### ISSUE THREAD

**Issue by eroux** [Esukhia/derge-tengyur-old#1]
vol. 197 p. 377b l. 5, I think the numbers must be read in column, not in line, and the one at the beginning of the line looks wrong in the input (missing a digit), but I don't know how to read them so I can't fix it myself

**Comment by ngawangtrinley** [comment]
don't delete!
![ssktlenmarkers](https://user-images.githubusercontent.com/17675331/45107718-106e0f00-b16d-11e8-9759-9f169bce3c48.png)

![ssktlenmarkers2](https://user-images.githubusercontent.com/17675331/45107711-0cda8800-b16d-11e8-8f85-19728bf41123.png)
